version: "3.2"

networks:
  frontend:
  backend:


services:

  webmvc:
    build: 
      context: .\src\Web\WebMvc
      dockerfile: Dockerfile
    environment: 
      - ASPNETCORE_ENVIRONMENT=Development 
      - CatalogUrl=http://catalog
      - IdentityUrl=http://10.0.75.1:5000
    container_name: webshop
    ports:
      - "6200:80"
    networks:
      - frontend 
    depends_on:
      - catalog
      - tokenserver
             


  catalog:
    build: 
      context: .\src\Services\ProductCatalogApi
      dockerfile: Dockerfile
    environment: 
      - ASPNETCORE_ENVIRONMENT=Development 
    container_name: catalogapi
    ports:
      - "5100:80"
    networks:
      - backend
      - frontend 
    depends_on:
      - mssqlserver
      

  tokenserver:
    build: 
      context: .\src\Services\TokenServiceApi
      dockerfile: Dockerfile
    environment: 
      - ASPNETCORE_ENVIRONMENT=Development 
      - MvcClient=http://localhost:6200   
    container_name: tokenserviceapi
    ports:
      - "5000:80"
    networks:
      - backend
      - frontend 
    depends_on:
      - mssqlserver


  mssqlserver:
    image: "microsoft/mssql-server-linux:latest"
    container_name: mssqldata
    ports:
      - "6000:1433" 
    networks:
      - backend
    environment:
      - SA_PASSWORD=MyProduct!123
      - ACCEPT_EULA="Y"
      

    